Hw3 ovsianko vlad
kairos-66/git-lesson pull request #12
Opened 2022-03-19 18:02 UTC by kevinlobster

Did homework №3

2022-03-20 13:22 UTC, kairos-66 requested changes

2022-03-20 13:22 UTC, kairos-66 commented on homeworks/hm1-ovsianko/hw3/index.html
> +<!DOCTYPE html>
The folder structure should be -

`homeworks/ovsianko/hw1` and `homeworks/ovsianko/hw3` for current homework.

2022-03-20 13:22 UTC, kairos-66 commented on homeworks/hm1-ovsianko/hw3/index.html
> +            <a class="nav-link active" aria-current="page" target="_blank"
Tags should have the same quantity of spaces ( tabs ) for the open and close tags.

<a>

2022-03-20 13:22 UTC, kairos-66 commented on homeworks/hm1-ovsianko/hw3/index.html
> +
Looks like useless empty line

2022-03-20 13:22 UTC, kairos-66 commented on homeworks/hm1-ovsianko/hw3/index.html
> +
the same below, please check

2022-03-20 13:22 UTC, kairos-66 commented on homeworks/hm1-ovsianko/hw3/style.css
> +html {background-color: #212429;}
Could you please make the same codestyle for each block?

```
selector {
  style: value;
}
```

2022-03-20 13:22 UTC, kairos-66 commented on homeworks/hm1-ovsianko/hw3/style.css
> +.table1 {background-color: rgb(25 27 31) !important;}
`important` is bad practice. The only one case when we should use it - rewriting inline styles

2022-03-20 13:22 UTC, kairos-66 commented on homeworks/hm1-ovsianko/hw3/style.css
> +    margin: auto; /* Выравниваем таблицу по центру окна  */
Russian text is not good practice in development because developers from other countries don't know russian.

2022-03-20 13:22 UTC, kairos-66 commented on homeworks/hm1-ovsianko/hw3/style.css
> +    text-align: left; /* Выравниваем текст по центру ячейки */
Rule `text-align: left` has the same meaning all the time. The comment is not useful.

2022-03-20 13:22 UTC, kairos-66 commented on homeworks/hm1-ovsianko/hw3/style.css
> +::placeholder {
This rule changes all placeholders you have. Suggestion - change only for specific input

2022-03-20 15:11 UTC, kevinlobster commented on homeworks/hm1-ovsianko/hw3/index.html
> +<!DOCTYPE html>
Done

2022-03-21 01:31 UTC, kevinlobster commented on homeworks/hm1-ovsianko/hw3/style.css
> +.table1 {background-color: rgb(25 27 31) !important;}
Done

2022-03-21 01:34 UTC, kevinlobster commented on homeworks/hm1-ovsianko/hw3/index.html
> +            <a class="nav-link active" aria-current="page" target="_blank"
done

2022-03-21 01:44 UTC, kevinlobster commented on homeworks/hm1-ovsianko/hw3/style.css
> +html {background-color: #212429;}
I will have a question about this, I will ask it at the next lesson on Tuesday.

2022-03-21 01:45 UTC, kevinlobster commented on homeworks/hm1-ovsianko/hw3/style.css
> +    margin: auto; /* Выравниваем таблицу по центру окна  */
Done

2022-03-21 01:48 UTC, kevinlobster commented on homeworks/hm1-ovsianko/hw3/style.css
> +    text-align: left; /* Выравниваем текст по центру ячейки */
Done

2022-03-21 02:04 UTC, kevinlobster commented on homeworks/hm1-ovsianko/hw3/style.css
> +::placeholder {
I don't wanna rework this .
I wanna all placegolders .
I will have question at next lesson.

2022-03-21 13:31 UTC, kairos-66 approved these changes

2022-03-21 13:31 UTC, merged